### ISSUE TITLE
Cannot install @loaders.gl/gltf

### ISSUE THREAD

**Issue by galleon** [uber-web/loaders.gl#102]
(deckgl) alleon_g$ npm i @loaders.gl/gltf --save
npm ERR! path /Users/alleon_g/0x-TechWork/jsbsim-react/jsbsim-view/node_modules/@loaders.gl/gltf/bin/glbdump.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/alleon_g/0x-TechWork/jsbsim-react/jsbsim-view/node_modules/@loaders.gl/gltf/bin/glbdump.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alleon_g/.npm/_logs/2019-02-28T05_30_59_335Z-debug.log

**Comment by ibgreen** [comment]
@galleon Thanks for reporting! 

Just published 0.7.1, worked in quick test, please give it a try.

Sorry for this, we are still iterating fast on loaders.gl, some breakages may happen. To compensate, we'll try to be responsive.
