### ISSUE TITLE
GLB JSON chunk length does not include padding 

### ISSUE THREAD

**Issue by jlisee** [uber-web/loaders.gl#206]
The issue is present in `@loaders.gl/gltf` at `1.0.3` as used in `@xviz/builder` at `v1.0.0-beta.10`, but appears fixed in by #179.  @twojtasz and @ibgreen not sure if belongs in #7 at all, but wanted to file this separately so I can note the work around I have to do in another library.

Specifically the older code [wrote the un-padded length](https://github.com/uber-web/loaders.gl/blob/v1.0.3/modules/gltf/src/glb/glb-builder.js#L197) out to the GLB file while [in the new code it is fixed](https://github.com/uber-web/loaders.gl/blob/master/modules/gltf/src/glb/encode-glb.js#L37-L42).

**Comment by ibgreen** [comment]
The GLB parser and encoder was rewritten to handle reading from/writing to non-zero offsets in the arrayBuffer. This was done to be able to extract embedded GLB-encoded GLTF files from 3D Tiles.

And yes, looks like it was fixed in this rewrite.

**Comment by ibgreen** [comment]
Given that the old code is now deprecated and I believe that XVIZ has moved to using the new code, will close this without fixing.
