### ISSUE TITLE
Publish new module versions with LICENSE file

### ISSUE THREAD

**Issue by bclinkinbeard** [uber-web/loaders.gl#235]
As of https://github.com/uber-web/ocular/pull/197, published modules properly include their full license text. deck.gl has [published](https://github.com/uber/deck.gl/issues/3151#issuecomment-497133270) v7.0.10 in response, can this repo do the same? Thanks!

**Comment by ibgreen** [comment]
- https://unpkg.com/@loaders.gl/core@1.1.0/LICENSE
