### ISSUE TITLE
glTF: texture.sampler is optional

### ISSUE THREAD

**Issue by donmccurdy** [uber-web/loaders.gl#259]
I'm seeing the following error on this sample model:

> gltf-post-processor-old.js:175 glTF file error: Could not find samplers[undefined]

The `texture.sampler` property is not required, and can use a default value if unspecified:

![Screen Shot 2019-06-17 at 3 16 49 PM](https://user-images.githubusercontent.com/1848368/59640471-04a77400-9113-11e9-865e-a325995aef9d.png)

[willow2.glb.zip](https://github.com/uber-web/loaders.gl/files/3299043/willow2.glb.zip)

**Comment by donmccurdy** [comment]
A simpler version of the same model (no textures) isn't showing any errors, but also isn't rendering for me. Not sure if that's my mistake or a bug in the loader.

[willowSolid.glb.zip](https://github.com/uber-web/loaders.gl/files/3299059/willowSolid.glb.zip)

**Comment by ibgreen** [comment]
@donmccurdy Thanks for reporting. I put up a quick PR, please check. I read the spec and assumed "auto filtering" is equivalent to using the default WebGL filtering values...

The glTF text: "When undefined, a sampler with repeat wrapping and auto filtering should be used." 

What is the license of your simplified sample? Is it something that could be contributed to the repo to include in render tests?

**Comment by donmccurdy** [comment]
Thanks! The sample is CC-BY Attribution:

- Elm: https://poly.google.com/view/68OOL4zL6Co
- Sycamore: https://poly.google.com/view/2S3-H6XeXyC
- Willow: https://poly.google.com/view/74_FuSwEd0E
- Ash: https://poly.google.com/view/23TdGBi6jmv

The untextured version doesn't look like much, so if you care about that it might be aesthetically nicer to use the original with a smaller texture.

**Comment by ibgreen** [comment]
published v1.1.2

**Comment by donmccurdy** [comment]
Thanks! The model is loading correctly now. :)
