### ISSUE TITLE
Broken 'getting started' link on website

### ISSUE THREAD

**Issue by rotoglup** [uber-web/loaders.gl#261]
The link on loaders.gl site points to https://loaders.gl/docs/get-started, and gives a GitHub pages error.

**Comment by ibgreen** [comment]
@rotoglup Thanks for reporting. The doc is available in https://loaders.gl/docs/developer-guide/get-started it is just the link that is broken.

@javidhsueh @jckr We need to make the `get-started` link configurable in ocular-gatsby.

**Comment by ibgreen** [comment]
Finally fixed, thanks for reporting!
