### ISSUE TITLE
@loaders.gl/3d-tiles: Load ion tilesets

### ISSUE THREAD

**Issue by loshjawrence** [uber-web/loaders.gl#284]
Talked to Sean, here's the documentation for making requests to ion
https://cesium.com/docs/tutorials/rest-api/
https://cesium.com/docs/rest-api/#section/Overview
https://cesium.com/docs/rest-api/#operation/getAssetEndpoint

### Example code to retrieve a list of assets available with the supplied accessToken
> const request = require('request-promise');
> const accessToken = '<your_access_token>'; // Replace this with your token from above.
> const response = await request({
>     url: 'https://api.cesium.com/v1/assets',
>     headers: { Authorization: `Bearer ${accessToken}` },
>     json: true
> });

This returns a json where where the `items` member contains an array of asset metadata. The `id` is used to request information about how to access it.
{"items":[{"id":1,"type":"3DTILES","name":"AGI HQ","description":"AGI Headquarters","bytes":0,"attributition":"AGI","dateAdded":"2019-05-29T18:56:13.088Z","status":"COMPLETE","percentComplete":100}, ...]}

### Example code to get information about the tileset related to an asset id:
> // Issue a GET request for the metadata
> const assetMetadata = await request({
>     url: `https://api.cesium.com/v1/assets/${assetId}/endpoint`,
>     headers: { Authorization: `Bearer ${accessToken}` },
>     json: true
> });

As an example, this could return something like:
> {
>   "type": "3DTILES",
>   "url": "https://assets.cesium.com/23912/tileset.json",
>   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyMjZmNzU0Yy02ZmVkLTQ4ODktOTUyMC0zMDRlMmNjODdiMzEiLCJpZCI6NDQsImFzc2V0cyI6eyIxIjp7InR5cGUiOiJURVJSQUlOIiwiZXh0ZW5zaW9ucyI6W3RydWUsdHJ1ZSx0cnVlXSwicHVsbEFwYXJ0VGVycmFpbiI6ZmFsc2V9fSwic3JjIjoiOGE2NjVmYmMtZDQzMy00ZmMxLWE3NDgtNjRhYWE3MjFiOTgzIiwiaWF0IjoxNTU0MTI4NTUzLCJleHAiOjE1NTQxMzIxNTN9.CWjqdF1LORmCd7nVbHupXyIjCPOfuSOpXwQoaQU_a94",
>   "attributions": [
>     {
>       "html": "<span><a href=\"https://cesium.com\" target=\"_blank\"><img alt=\"Cesium ion\" src=\"http://assets.cesium.com/ion-credit.png\"></a></span>",
>       "collapsible": false
>     }
>   ]
> }

Looking at https://cesium.com/docs/rest-api/#operation/getAssetEndpoint
the url is for the tileset.json and the accessToken is as specified:
> The token to be included with each tile request, using Bearer format. This token is different than the access token used throughout the rest of the REST API. It provides access to the asset for approximately one hour. To continue using the asset after the allotted time, simple re-request the endpoint for a new token.

**Comment by ibgreen** [comment]
@loshjawrence Initial implementation, should allow specifying `?ionAccessToken=` in the URL and should autoload first TILES3D resource from that token.

**Comment by loshjawrence** [comment]
Updated the instructions, was missing /endpoint in the url when querying the asset's url and access token
