### ISSUE TITLE
GLTFScenegraph: addBufferView is broken

### ISSUE THREAD

**Issue by MGraefe** [uber-web/loaders.gl#297]
`addBufferView` in gltf-scenegraph.js is handling the bufferOffset incorrectly which causes `addImage` to be broken.

- `this.byteLength` is not initialized
- `this.byteLength += padTo4Bytes(byteLength);` has to be done _after_ `glTFBufferView` is constructed

This looks like an easy fix but I currently have no working dev setup so I would be very glad if this could be fixed.

**Comment by ibgreen** [comment]
@MGraefe Try `1.2.0-beta.2` (and apologies for the slow response, was out of office).
