### ISSUE TITLE
Can loaders work with rollup? 

### ISSUE THREAD

**Issue by nshen** [uber-web/loaders.gl#372]
I can't make it work with rollup? any example? thanks

**Comment by ibgreen** [comment]
@nshen Yes, we absolutely want loaders.gl to work with rollup. 

We don't use rollup ourselves, so unfortunately no examples.

If you can provide more information it might help us understand what needs to be fixed.

**Comment by nshen** [comment]
> @nshen Yes, we absolutely want loaders.gl to work with rollup.
> 
> We don't use rollup ourselves, so unfortunately no examples.
> 
> If you can provide more information it might help us understand what needs to be fixed.

Thanks for reply.

I just clone rollup-start-app `https://github.com/rollup/rollup-starter-app`

then I add some simple code like this

``` javascript

async function test(){
    let objfile = await fetch('https://raw.githubusercontent.com/uber-web/loaders.gl/master/modules/obj/test/data/cube.obj');
    console.log(objfile)
}
test();
```

then run `yarn build`

that works fine in my browser. then I just follow gettting start section of the website


``` javascript

import {parse} from '@loaders.gl/core';
import { OBJLoader } from "@loaders.gl/obj";

test();


async function test(){
    const data = await parse(fetch('https://raw.githubusercontent.com/uber-web/loaders.gl/master/modules/obj/test/data/cube.obj'),OBJLoader);
    console.log(data)
}
```
when I build it said

> 
> (!) Missing shims for Node.js built-ins
> Creating a browser bundle that depends on 'util'. You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
> (!) Plugin node-resolve: preferring built-in module 'fs' over local alternative at 'fs', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> (!) Plugin node-resolve: preferring built-in module 'util' over local alternative at 'util', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> (!) Unresolved dependencies
> https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
> fs (imported by node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js, node_modules/@loaders.gl/core/dist/esm/node/read-file-sync.node.js)
> util (imported by node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js)
> (!) Missing global variable names
> Use output.globals to specify browser global variable names corresponding to external modules
> fs (guessing 'fs')
> util (guessing 'util')
> 

then I tried to change some config of rollup plugin, but still can't make it work.

**Comment by ibgreen** [comment]
My guess from your trace is that rollup is not respecting the `browser` field in package.json by default:

https://github.com/rollup/rollup-plugin-node-resolve/blob/master/README.md#L55

As a first step, try enabling it and see if that makes a difference.

**Comment by nshen** [comment]
I already tried various fields

```
export default {
	input: 'src/main.js',
	output: {
		file: 'public/bundle.js',
		format: 'iife', // immediately-invoked function expression — suitable for <script> tags
		sourcemap: true
	},
	plugins: [
		resolve({
			browser: true,
		}), // tells Rollup how to find date-fns in node_modules
		commonjs(), // converts date-fns to ES modules
		production && terser() // minify, but only in production
	]
};
```
output is same:

```
src/main.js → public/bundle.js...
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'util'. You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
(!) Plugin node-resolve: preferring built-in module 'util' over local alternative at 'util', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
util (imported by node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
util (guessing 'util')
created public/bundle.js in 2.3s
```
then I add `preferBuildins:false`
```
resolve({
	browser: true,
	preferBuiltins: false
}), 
```
out
```
src/main.js → public/bundle.js...
[!] (plugin Rollup Core) Error: Could not load util (imported by /mnt/e/code/rollup-starter-app/node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js): ENOENT: no such file or directory, open 'util'
Error: Could not load util (imported by /mnt/e/code/rollup-starter-app/node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js): ENOENT: no such file or directory, open 'util'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ibgreen** [comment]
Looks like you are trying the right things. I'd need to set up an example and start experimenting to get further.

Do you think you could open a PR with the config above and a package.json that installs all the necessary rollup plugins, that I could use as a base?

Something in `examples`, or maybe better put something really minimal in a `test/apps` folder?

**Comment by ibgreen** [comment]
Thanks for the PR! Interestingly on my machine, your configuration worked without errors. 

I made some changes to the example so that it works with `yarn serve`, will push in separate PR.

PS - The linter errors are easily fixed by running `yarn lint fix`.

**Comment by ibgreen** [comment]
Closing as this works for me now. Happy to keep discussing if you cannot replicate.
