### ISSUE TITLE
3d-tiles: Traversal issues for REPLACEMENT tilesets (Disappearing tiles)

### ISSUE THREAD

**Issue by ibgreen** [uber-web/loaders.gl#384]
b3dm models like the vricon examples are not ADDITIVE but use REPLACEMENT to display child tiles instead of parent tiles when zooming in.

In the current traversal implementation, the parent tiles are hidden before the child tiles load, leading to a quite jarring effect:

![cairo](https://user-images.githubusercontent.com/7025232/64435523-80142400-d077-11e9-8dcb-4568f7f3db15.gif)

Also: There is also an issue that tiles disappear after a while. Could it be that once culled they won't show up again? This could be deck.gl/webgl related, but it has not been ruled out that this could be a traversal issue.

There are some WebGL errors in the console but preliminary fixes didn't address the "disappearing tiles" problem.

**Comment by loshjawrence** [comment]
The most likely issue is that we are switching a tile state too early. A tile-3d-header has a few states like UNLOADED, LOADED, PROCESSING, READY... or something like that. One of those is used to indicate that the gpu resource has been created and its able to render this frame if you want it to. We should only switch to the ready-to-render state when the layer is ready to go.

**Comment by loshjawrence** [comment]
So the side effect of switching too early is that traversal sees that all the children have this state (erroneously) turned on so it thinks "ok, no need have the parent placehold since the children are ready to go".

**Comment by ibgreen** [comment]
That makes sense. There is a level of "asynchronicity" in the current loading approach - the embedded gltf tile is not loaded by the tile loader, but separately by the `Tile3dLayer`.

It will take some work to change so I was thinking I could push it off until after initial release, but perhaps it will help in this situation, so I should bite the bullet now.

I will update you on how it goes.

**Comment by loshjawrence** [comment]
> I wonder if it is related to the fact that the mapbox camera sync moves the camera too close to the ground?
> And vegas being at a higher elevation.

Current issue seems to be something like this. Printing out a high water mark number for what was the deepest tree depth it drilled down to in any part of the tree, it seems to go back up once you get close enough to the ground (example printing code here: https://github.com/loshjawrence/loaders.gl/commit/1e4965205ef5f4013226b8fd5c76175e57cbc1c8)

**Comment by ibgreen** [comment]
This appears to work now.

**Comment by vanness30214** [comment]
I would like to ask, how is the progress of the problem now? Thank you

**Comment by ibgreen** [comment]
AFAIK this issue was fixed in 2019. I have not seen any indication that there has been a regression. I recommend you open a thread in discussions section if you have problems.
