### ISSUE TITLE
glTF BufferView Stride is not taken into account

### ISSUE THREAD

**Issue by georgios-uber** [uber-web/loaders.gl#45]
https://github.com/uber-web/loaders.gl/blob/ecbca8a9c76aa3482d02198342f825c9e406b819/modules/gltf/src/glb/unpack-glb-buffers.js#L65

**Comment by ibgreen** [comment]
My understanding is that `stride` is a property of the glTF accessor (not the bufferView) and is used when setting a GPU vertex attribute to the resulting GPU buffer as a vertex attribute using `gl.vertexAttribPointer`. 

There is to my knowledge no way to specify typed arrays with strides on the JavaScript side, only on the GPU side.

luma.gl should support stride so it is just a question of creating a luma.gl accessor based on the glTF accessor.

**Comment by georgios-uber** [comment]
According to [the official spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-bufferview) a buffer view has an optional **byteStride**. The **2CylinderEngine.glb** sample is using it.
> The stride, in bytes, between vertex attributes. When this is not defined, data is tightly packed. When two or more accessors use the same bufferView, this field must be defined.

According to the [hand-book](https://www.khronos.org/files/gltf20-reference-guide.pdf)
> The accessor defines a stride between the elements


Which one is the right one?

**Comment by ibgreen** [comment]
Hmm, yes I see. 

In luma.gl we only have a single class `Accessor` to describe how a vertex attribute should "access" memory, so my assumption is that we will have to merge the appropriate fields from the glTF bufferView and accessor into the luma.gl `Accessor`. 

We should probably update the `gltf-mapping.md` doc with the details.

**Comment by georgios-uber** [comment]
I think the _hand-book_ is wrong, I think we only need to implement the **byteStride** on **buffer view**

**Comment by georgios-uber** [comment]
#71 fixes this.
