### ISSUE TITLE
glTF: unpackImage does not exist

### ISSUE THREAD

**Issue by georgios-uber** [uber-web/loaders.gl#46]
https://github.com/uber-web/loaders.gl/blob/ecbca8a9c76aa3482d02198342f825c9e406b819/modules/gltf/src/gltf/gltf-parser.js#L311

**Comment by ibgreen** [comment]
Oops you are right, looks like it is called `glbParser.getImage`.

**Comment by georgios-uber** [comment]
Thanks, I'll send a PR.
