### ISSUE TITLE
glTF mesh/camera/skin 0 do not load

### ISSUE THREAD

**Issue by georgios-uber** [uber-web/loaders.gl#47]
https://github.com/uber-web/loaders.gl/blob/ecbca8a9c76aa3482d02198342f825c9e406b819/modules/gltf/src/gltf/gltf-parser.js#L222

**Comment by ibgreen** [comment]
Yes I see, the usual gotcha! Maybe use 

```
if ('mesh' in node) {
```

or 

```
if (Number.isFinite(node.mesh)) {
```

**Comment by georgios-uber** [comment]
I prefer `!== undefined`
