### ISSUE TITLE
ocular-clean 

### ISSUE THREAD

**Issue by VINOlive** [uber-web/loaders.gl#522]
PR: "build": "ocular-clean && lerna run pre-build && ocular-build"
Error: loaders.gl@ build: `ocular-clean && lerna run pre-build && ocular-build`
System can not find the route.

Only linux and mac os need?
How to run at win 10
Any help thank u

**Comment by xintongxia** [comment]
@VINOlive 

Did you follow this link to install the development environment?

https://github.com/uber-web/loaders.gl/blob/master/docs/contributing.md

Another thing you may probably need is put the `loaders.gl` following the linux directory convention.

For example, you can download loaders.gl to your linux home directory, simply as `~/loaders.gl`. If you use window directory, it may cause some troubles.

**Comment by VINOlive** [comment]
> @VINOlive
> 
> Did you follow this link to install the development environment?
> 
> https://github.com/uber-web/loaders.gl/blob/master/docs/contributing.md
> 
> Another thing you may probably need is put the `loaders.gl` following the linux directory convention.
> 
> For example, you can download loaders.gl to your linux home directory, simply as `~/loaders.gl`. If you use window directory, it may cause some troubles.


> @VINOlive
> 
> Did you follow this link to install the development environment?
> 
> https://github.com/uber-web/loaders.gl/blob/master/docs/contributing.md
> 
> Another thing you may probably need is put the `loaders.gl` following the linux directory convention.
> 
> For example, you can download loaders.gl to your linux home directory, simply as `~/loaders.gl`. If you use window directory, it may cause some troubles.

Thank you.  I compile in window environment.  I just want to use vm linux to compile this program.
