### ISSUE TITLE
plyloader do not render color

### ISSUE THREAD

**Issue by zt123123** [uber-web/loaders.gl#528]
I use plyloader to load text ply file:
the file like this:
ply
format ascii 1.0
element vertex 302911
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
-500.063079833984375 22.3280677795410156 21.7964668273925781 0 0 255
-500.24517822265625 22.5292701721191406 21.8051128387451172 0 0 255
......
the model is show, but is does not show the color,
![image](https://user-images.githubusercontent.com/18349295/68575594-575d4000-04a7-11ea-848f-e039dcd67fc6.png)

**Comment by zt123123** [comment]
ps: the console shows a warning msg as following:
deck: Attribute instanceColors is normalized

**Comment by xintongxia** [comment]
Do you mind providing a ply dataset url for me to debug?

**Comment by zt123123** [comment]
[0.ply.zip](https://github.com/uber-web/loaders.gl/files/3834100/0.ply.zip)
thanks! here is a local file

**Comment by zt123123** [comment]
> Do you mind providing a ply dataset url for me to debug?

[0.ply.zip](https://github.com/uber-web/loaders.gl/files/3840760/0.ply.zip)
thanks! here is a local file

**Comment by zt123123** [comment]
> Do you mind providing a ply dataset url for me to debug?

debug find the COLOR_0 array type seems incorrect, it should be Float32Array type
![image](https://user-images.githubusercontent.com/18349295/69113200-4a4edb00-0abd-11ea-97d4-76deb092147c.png)

**Comment by zt123123** [comment]
@xintongxia When parse the PLY file, the `color` properties has been convert to range [0, 1] from [0, 255] by divided by 255. But when normalize the array of color to a typed array, use `UInt8Array` or not `Float32Array`. I guess the coder forgot the converting color range, and I never find any example using PLY file can render color ..... List the code, FYR...

https://github.com/uber-web/loaders.gl/blob/8ab249f45cc5e7d1ea7bdbae05f3d268fc3a6253/modules/ply/src/lib/parse-ply.js#L247

https://github.com/uber-web/loaders.gl/blob/8ab249f45cc5e7d1ea7bdbae05f3d268fc3a6253/modules/ply/src/lib/normalize-ply.js#L38

**Comment by ibgreen** [comment]
@zt123123 Confirmed, it looks like have indeed found a bug on line 247. 

Looking in [PLY format](http://paulbourke.net/dataformats/ply/) description, the examples clearly show `uchar` color values are between 0-255 in the PLY source. And `Uint8Arrays` also need to have values between 0-255. So there should be no division with 255 in that case.

**Comment by zt123123** [comment]
@ibgreen  when you update npm package ?

**Comment by ibgreen** [comment]
@xintongxia I think we need to back port this commit to make a 1.3.x patch.

**Comment by xintongxia** [comment]
@zt123123 1.3.5 published with ply fix.

**Comment by zt123123** [comment]
@xintongxia @ibgreen   thanks, the problem has been resolved
