### ISSUE TITLE
@loaders.gl/images is missing dependency for @loaders.gl/loader-utils

### ISSUE THREAD

**Issue by snosenzo** [uber-web/loaders.gl#634]
Got this error during build due to a package using the `@loaders.gl/images: "2.0.2"` dependency: 
```
error: (client) ./node_modules/@loaders.gl/images/dist/esm/lib/texture-loading-api/generate-url.js 53:9-20
"export 'resolvePath' was not found in '@loaders.gl/loader-utils'
```
Upon looking at the `package.json` inside of `@loaders.gl/images` there is not dependency for `@loaders.gl/loader-utils`, so I think that `package.json` just needs to be updated with that dependency.

In the mean time, I've added `@loaders.gl/loader-utils` as a direct dependency to my project.

Let me know if I'm wrong or you need any more info.

**Comment by ibgreen** [comment]
@snosenzo Sounds like the missing dependency would indeed be a bug, not critical since you have a workaround, but we'll get it fixed soon.

**Comment by snosenzo** [comment]
Thanks! sounds good
