### ISSUE TITLE
Extract features by layer with MVTLoader

### ISSUE THREAD

**Issue by kylebarron** [uber-web/loaders.gl#674]
In the new `MVTLoader`, it appears that features from all layers of the vector tile are flattened upon loading. This omits significant information from the source vector tile representation: namely the layer that each feature comes from.

In my opinion, a closer representation to the source tile would be:
```json
{
  "layer1": [
    {"type": "Feature", "geometry": "..."},
    {"type": "Feature", "geometry": "..."}
  ],
  "layer2": [
    {"type": "Feature", "geometry": "..."},
    {"type": "Feature", "geometry": "..."}
  ]
}
```

Also, while protobuf parsing appears to be quite fast, it might be worthwhile to add a `layers` option, as an array of strings, to identify layers to parse.

I.e.
```js
const loaderOptions = {
  mvt: {
    layers: ["layer1"]
  }
};
const geoJSONfeatures = await load(url, MVTLoader, loaderOptions);
```

```json
{
  "layer1": [
    {"type": "Feature", "geometry": "..."},
    {"type": "Feature", "geometry": "..."}
  ]
}
```

So if the vector tile has 50 layers, but you only care about 2, you could speed up parsing.

**Comment by ibgreen** [comment]
@kylebarron This is good feedback and reasonable proposals.

We can certainly discuss adding special options to a particular loader, however at the very least we should make sure the layer information is still present in the geojson the loader return now. 

A first option could be to make sure the layer name is present in to the `properties` object of each feature so you could get the layers array and filter as follows:

```js
const layers = Array.from(features.reduce((set, feature) => set.add(feature.properties.layer), new Set())))l
const layerFeatures = features.filter(feature => feature.properties.layer === );
```

We could add such code snippets to the documentation page to get users on the right track. 

When it comes to more custom loader output, I am a little hesitant to change the output format of the loader, since the general idea of loaders.gl is to create categories of loaders that output format that can be handled in the same way by the application, and we have a growing set of loaders that output "pure" geojson.

Do you have any numbers on the number of features in your tiles that would strengthen the case for more custom options?

@jesusbotella

**Comment by jesusbotella** [comment]
Thank you for your feedback!

As you say, features within layers are flattened into a single array of GeoJSON objects and it seems like important metadata is lost, like the name of the layer that the feature belongs to. However, we would need to avoid GeoJSON properties collision (when having another property named `layer` within MVT features) when adding it to the decoded GeoJSON object.

About adding a new `layers` option, I think it would be a great optional feature for developers that want to avoid parsing all layers if they don't need them. By default, we parse all layers, and if the `layers` option is present, we will only parse the "selected" ones. That said, improvements may not be high, it depends on the number of features that your MVT has, but it is very fast parsing features.

And as @ibgreen say, I wouldn't change the output format. For me, an array containing GeoJSON objects is easier to use and modify than an object with layer names as string keys.

**Comment by kylebarron** [comment]
Here's my use case: I'm really excited about deck.gl's new TerrainLayer, and I'm trying to display tiled vector features on the terrain surface. My plan is to [snap](https://github.com/kylebarron/snap-features-to-mesh/) the `Point` and `LineString` features to the mesh output of the `TerrainLoader`, adding altitudes to each coordinate and creating new coordinates where lines cross mesh edges, and then use a Mapbox Style Spec-like JSON document to autogenerate Deck.gl `IconLayer`s, `PathLayer`s, and `TextLayer`s.

Like a Mapbox style, I'm thinking of having a layer description be something like
```json
{
  "layers": [
    {
      "id": "layerid",
      "source": "openmaptiles",
      "source-layer": "transportation",
      "type": "PathLayer",
      PathLayer props...
    }
  ]
}
```
in which case I would need to know the layer each feature comes from.

> A first option could be to make sure the layer name is present in to the `properties` object of each feature so you could get the layers array and filter as follows

I didn't initially suggest this because I too was worried for the possibility of feature property name collisions. I suppose that if you take a rare enough name and add it to the documentation, it should be fine.

As for the `layers` option, I understand that pbf parsing is already quite fast, so this isn't a big issue for me. I'm using the OpenMapTiles schema, and a tile covering western SF has 5000 features:
```
> vt2geojson https://mbtiles.nst.guide/services/openmaptiles/us/tiles/12/654/1583.pbf | jq -c '.features[]' | wc -l
5148
```
I mention this option partially because it seems very simple to add. Just an extra line here?
https://github.com/uber-web/loaders.gl/blob/41e8ec71a7e1c1df5f0f8909839b8e871caacfcd/modules/mvt/src/lib/parse-mvt.js#L20

**Comment by ibgreen** [comment]
> and a tile covering western SF has 5000 features:

Thanks that is helpful, and I am assuming you don't need the majority of those features. Multiply that with a hundred tiles and it starts to get significant.

I'd be fine with adding an option to avoid generating features for layers the app is not planning to use. No need to use up more space than we need, or provoke the garbage collector if we don't have to.

How about this as first idea (spec:ed as addition to the docs)?

| Option |Type | Description |
| --- | --- |  --- |
| `options.mvt.layers` |  `string[]`  | Optional list of layer names. If supplies, only features belonging to the named layers will be included in the output. If not supplied, features from all layers are returned. |
| `options.mvt.layerProperty` | `string` | If provided, the layer name is added to `feature.properties[layerProperty] (first adds a `feature.property` object is created if it did not already exist). |

There are some choices on the `layerProperty` prop - if it has a default, how it handles collisions, if it can be set to `null` etc.

**Comment by kylebarron** [comment]
Oh I like that! I didn't think of having the property for the layer name being user-provided.

I'd be fine with the `layerProperty` default being `null`, where the layer name isn't added to the features at all. I'm not sure what the best solution is when the provided `layerProperty` string is the same as a feature's property name.

**Comment by jesusbotella** [comment]
I'd add a `layer` property within GeoJSON feature properties by default, and use `layerProperty` option only when there's an existing `layer` property within feature properties. 

Let me open a Pull Request with those changes, and we can discuss non-default behaviours there!

**Comment by kylebarron** [comment]
To me that seems confusing, because the value of `layer` depends on the content of the vector tile, so you won't know whether `layer` is the layer's name or a feature property until _after_ the tile is parsed.

**Comment by jesusbotella** [comment]
I assumed that you knew the properties schema before parsing the MVT.

So, what would be better for you? Setting the name to the property provided in `layerProperty` whether there is a property named `layer` or not? It would happen the same I guess but you can define it in advance at least.

**Comment by kylebarron** [comment]
Well in this particular situation I do, but I wouldn't necessarily assume that everyone using `MVTLoader` in the future does with their arbitrary tile sources.

I think I would have `layerProperty` set to `null` by default, and if non-null, it overwrites a property named the value of `layerProperty` if it exists. But make this clear in the docs.

In any case, I'll defer to @ibgreen

**Comment by ibgreen** [comment]
Hmm, I see both viewpoints. I would go with @jesusbotella's proposal here, i.e. we can set the `layer` prop by default, since we do offer the . It seems like this is a natural bit of information to provide for a format that is so heavily layer based. 

It might be good to first verify with 2-3 major tiles sources (a mapbox tile, the openmaptile you linked above etc) if they all use `layer` in a way that is incompatible with our proposed use, we could reconsider.

**Comment by kylebarron** [comment]
The [Mapbox Streets v8 schema](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#layer-reference) has a `layer` property field [in its `road` layer](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#--road---layer-number).

> The layer field is used to determine drawing order of overlapping road segments in the tunnel and bridge layers.

So when loading a Mapbox Streets vector tile, `layer` would already be defined for features in the `road` layer.

**Comment by ibgreen** [comment]
underscores are usually safe but a little bit too ugly / defensive if we can avoid them. 

How about we call it `layerName`?

**Comment by kylebarron** [comment]
Sounds good to me.
