### ISSUE TITLE
Flat binary arrays followup

### ISSUE THREAD

**Issue by kylebarron** [uber-web/loaders.gl#702]
Resuming from #685, #690 

- **Index array length** - We should indeed make index arrays one element longer and include the length as final index.
- **Mixed coordinate dimensions**. If only some of the coordinates have 3 dimensions, some values in `positions` will be off by 1. If it's important to support varying coordinate dimensions, this needs to be fixed.
- **Feature properties**. The options are 1) convert numeric properties to binary arrays, 2) return an array of property objects with each geometry type 3) not returning properties. It might be worthwhile to implement 1 and 2, and let usage be user-decided.

	For 2, should `objectIds` point to the index in its local `properties` array? I.e. here, `points.objectIds` points to `points.properties`?
	
	```js
	{
	  points: {
	    // Array of x, y or x, y, z positions
	    positions: {value: Float32Array, size: coordLength},
    	// Array of original feature indexes by vertex
	    objectIds: {value: Uint32Array, size: 1},
		// Array of property objects
		properties: [
			{...}
		]
	  },
	  ...
	}
	```

**Comment by ibgreen** [comment]
> Mixed coordinate dimensions. 

I trust we will agree that silently returning a malformed array is not acceptable, as the user could end up in a lot of pain trying to debug why that happened.

This is one of the reasons I propagated for the two-pass approach. If not specified, the first pass looks at all geometries and determines the max number of coords (2 or 3), and the second pass adjusts all coordinates to the desired length. I'd also be fine with just detecting a discrepancy and throwing an error.

> Feature properties. 

I would focus on the binary columnar table generation (case 1), and just leave `objectIds` into the original features array. 

We can add a note in the docs showing that it is trivial for the app to generate its own properties array 

```
objectIds.map(featureIndex => features[featureIndex.properties] || {});
```

**Comment by ibgreen** [comment]
One more point: I did some further reading on columnar table layouts and I was incorrect about your index question. We should indeed make index arrays one element longer and include the length as final index!

>> Currently the length of pathIndices is the same as the number of paths, not n + 1. I.e [0, 2, 5], and not [0, 2, 5, 9]. The last number is the same as the number of vertices; should I include it?

> From the perspective of returning a "columnar table", it is desirable that all columns with fixed-length elements are of the same length (as in number of rows).

**Comment by kylebarron** [comment]
**Feature properties**

In order to achieve the speed gains from transferring binary data, the point is for this code to be called from within the loader worker thread, right? So I'm still a little confused about properties because the `MVTLoader` has access to the `features` array, but the main thread _won't_, unless all `features` are serialized back to the main thread (which would remove most gains from creating binary arrays?). So if I run
```js
load(url, MVTLoader, {mvt: {binary: true}}
``` 
and if that only returns the output of `geojsonToBinary`, the `objectIds` array tells me nothing because I don't have access to the original `features`. 

So will `features` be serialized back to the main thread (perhaps stripped of `geometry` of each feature) or only arrays of numeric binary attributes?

Does that question make sense?

**Mixed coordinate dimensions**

> I trust we will agree that silently returning a malformed array is not acceptable, as the user could end up in a lot of pain trying to debug why that happened.

Yes, you're quite right. What should the "`nodata`" value be for mixed coordinates? I.e. if the `positions` array is initialized to 0, and there are mixed coordinates where a 2D position doesn't change the third coordinate, the user won't know that that `0` is actually representing missing data.

**Comment by ibgreen** [comment]
> the point is for this code to be called from within the loader worker thread

You have a great point. While your code is very generally useful, the fact that binary data can be handle efficiently on a worker, combined with loaders.gl having built-in support for workers, is of course a major bonus, and we should indeed optimize for that.  

So, yes:

- Serializing and deserializing "less JSON" between worker and main-thread is of course better, so makes sense to only pass along only the prop objects (including stripping away any props that were binarized).
- Yes, we may as well split into one such properties array each for points, lines and polygons.
- For the index choice: you could offer to create two binary objectId lists - name ideas: `globalFeatureId` and `featureId`?`globalObjectId` and `objectId`?  `globalFeatureIndex` and `featureIndex`?
- To save some space, you could make those lists use `Uint16Array` if you have less than 65K features...

Notes:
- You still have the multi-polygon issue (one prop can cover multiple binary features), so the array still won't be the same length as the individual lists...
