### ISSUE TITLE
3DTileLoader conflicts with non-3D tile JSON data

### ISSUE THREAD

**Issue by ajduberstein** [uber-web/loaders.gl#710]
It seems a .json file extension can be parsed by either the 3DTileLoader or JsonLoader. If both are registered within deck.gl, there is a conflict. Some JSON data sets fail to load if the 3DTileLoader is registered. 

![image](https://user-images.githubusercontent.com/2204757/77972633-cdbbdc80-72a6-11ea-9b6a-36e43c8484f1.png)

This is an issue for pydeck (Python bindings for deck.gl) at the moment–I can resolve it by registering the 3DTileLoader only if there is a 3DTileLayer being processed in the user's input.

**Comment by ibgreen** [comment]
There is supposed to be a mechanism for testing that the data is parsable by a specific loader. It would look for certain fields on the JSON before deciding it is a 3D tileset. 

It is not foolproof but should handle most cases, we should investigate first if this is still in place and working.

@xintongxia

**Comment by xintongxia** [comment]
> There is supposed to be a mechanism for testing that the data is parsable by a specific loader. It would look for certain fields on the JSON before deciding it is a 3D tileset.
> 
> It is not foolproof but should handle most cases, we should investigate first if this is still in place and working.
> 
> @xintongxia

v2.1 changed `Tiles3DLoader` to parse `tileset.json` and all the different tile (.b3dm, i3dm, pnts, etc) formats, so I added `json` to `extensions` and `test` of `Tiles3DLoader`

So I propose to remove `.json` from `Tiles3DLoader` and `I3SLoader`, and such that `Tiles3DLoader` and `I3SLoader` needs to be explicitly specified when using `load` to load a tileset.

**Comment by Pessimistress** [comment]
You shouldn't register `3DTileLoader`  in jupyter-widget. The `Tile3DLayer` will import the loader that it needs.

**Comment by ibgreen** [comment]
> So I propose to remove .json from Tiles3DLoader and I3SLoader, and such that Tiles3DLoader and I3SLoader needs to be explicitly specified when using load to load a tileset.

Yes that could make sense until we are able to refine the loader tests (although the issue seems to be solved now).

**Comment by xintongxia** [comment]
@ajduberstein
