### ISSUE TITLE
Make GLTFWorkerLoader

### ISSUE THREAD

**Issue by twojtasz** [uber-web/loaders.gl#93]
See https://github.com/uber-web/loaders.gl/pull/92

**Comment by ibgreen** [comment]
Not opposed to this, however my sense is that the benefits of moving gltf parser to a worker will be limited, as the amount of processing that would be moved to the worker is small and the amount of JSON that needs to be serialized/deserialized is big. It may overall be slower to load glTF through a worker.

Of course in some cases, if things like draco decompression were handled by the worker then it would be a different story, although those things could be done separately on workers as well. And currently we don't decompress on load but rather on access.

**Comment by ibgreen** [comment]
Closing this as top-level issue, it remains as item in the tracker tasks.
